# Generated by Django 3.2.10 on 2023-12-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('canteen_id', models.AutoField(primary_key=True, serialize=False, verbose_name='餐厅编号')),
                ('canteen_name', models.CharField(max_length=10, verbose_name='餐厅名称')),
                ('canteen_photo', models.ImageField(blank=True, null=True, upload_to='images/canteen', verbose_name='餐厅照片')),
                ('canteen_active', models.CharField(choices=[('营业中', '营业中'), ('歇业中', '歇业中')], max_length=10, verbose_name='食堂状态')),
            ],
            options={
                'verbose_name': '餐厅信息',
                'verbose_name_plural': '餐厅信息',
                'db_table': 'canteen',
                'ordering': ['canteen_id'],
            },
        ),
        migrations.CreateModel(
            name='ShopManager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False, verbose_name='负责人编号')),
                ('manager_name', models.CharField(max_length=20, verbose_name='负责人姓名')),
                ('manager_password', models.CharField(max_length=20, verbose_name='负责人密码')),
                ('manager_tel', models.CharField(max_length=11, verbose_name='负责人电话')),
                ('manager_status', models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=0, verbose_name='经营者状态')),
                ('manage_shop_num', models.IntegerField(verbose_name='负责窗口数')),
            ],
            options={
                'verbose_name': '窗口负责人信息',
                'verbose_name_plural': '窗口负责人信息',
                'db_table': 'shop_manager',
                'ordering': ['manager_id'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False, verbose_name='窗口编号')),
                ('shop_name', models.CharField(max_length=20, verbose_name='窗口名称')),
                ('shop_detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='窗口描述')),
                ('shop_photo', models.ImageField(blank=True, null=True, upload_to='images/shop', verbose_name='窗口照片')),
                ('shop_active', models.IntegerField(choices=[(1, '营业中'), (0, '歇业中')], verbose_name='窗口状态')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.canteen', verbose_name='餐厅')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='canteen.shopmanager', verbose_name='窗口负责人')),
            ],
            options={
                'verbose_name': '窗口信息',
                'verbose_name_plural': '窗口信息',
                'db_table': 'shop',
                'ordering': ['shop_id'],
            },
        ),
    ]
